export const productData = [
  {
    id: 1,
    name: "Intel Core i5-13600K",
    price: "2500 DH",
    rating: 4.7,
    sold: "700+ sold",
    image:
      "public/images/i5.webp",
  },
  {
    id: 2,
    name: "Acer Aspire 3 AMD Ryzen 3 7320U",
    price: "7500 DH",
    rating: 4.8,
    sold: "800+ sold",
    image: "public/images/lap.webp",
  },
  {
    id: 3,
    name: "Red Dead Redemption 2",
    price: "800 DH",
    rating: 4.6,
    sold: "400+ sold",
    image: "public/images/red.webp",
  },
  {
    id: 4,
    name: "Alienware Gaming PC",
    price: "12500 DH",
    rating: 4.9,
    sold: "900+ sold",
    image: "public/images/gd.webp",
  },
  {
    id: 5,
    name: "Razer DeathAdder V2 Gaming Mouse",
    price: "550 DH",
    rating: 4.5,
    sold: "600+ sold",
    image: "public/images/rm.webp",
  },
  {
    id: 6,
    name: "Corsair K70 RGB Gaming Keyboard",
    price: "1200 DH",
    rating: 4.7,
    sold: "500+ sold",
    image: "public/images/ck.webp",
  },
  {
    id: 7,
    name: "Samsung 970 EVO Plus SSD 1TB",
    price: "1400 DH",
    rating: 4.8,
    sold: "1000+ sold",
    image: "public/images/Samsung-970-EVO-Plus.webp",
  },
  {
    id: 8,
    name: "PlayStation 5",
    price: "8500 DH",
    rating: 4.9,
    sold: "1500+ sold",
    image: "public/images/PlayStation-5.jpeg",
  },
  {
    id: 9,
    name: "Nintendo Switch OLED",
    price: "4000 DH",
    rating: 4.6,
    sold: "700+ sold",
    image: "public/images/Nintendo-Switch-OLED.jpeg",
  },
  {
    id: 10,
    name: "Logitech G733 Wireless Headset",
    price: "900 DH",
    rating: 4.5,
    sold: "800+ sold",
    image: "public/images/lh.webp",
  },
  {
    id: 11,
    name: "MSI RTX 3060 Ti Gaming X",
    price: "4200 DH",
    rating: 4.7,
    sold: "300+ sold",
    image: "public/images/rx.webp",
  },
  {
    id: 12,
    name: "Apple MacBook Pro 14-inch",
    price: "22000 DH",
    rating: 4.8,
    sold: "150+ sold",
    image: "public/images/mac.webp",
  },
];
